name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Public IP
        id: get_ip
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Print Public IP
        run: echo "Public IP: ${{ env.PUBLIC_IP }}"

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "${{ env.PUBLIC_IP }}," ansible/ansible.yml \
            --user ubuntu --private-key <(echo "${{ secrets.PRIVATE_KEY }}")

      - name: Build and Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.PRIVATE_KEY }}") ubuntu@${{ env.PUBLIC_IP }} "
            docker build -t my-app .
            docker run -d -p 80:80 my-app
          "
