# .github/workflows/deploy.yml
name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Public IP
        id: get_ip
        run: echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i "${{ env.PUBLIC_IP }}," ansible-playbook.yml --user ubuntu --private-key ${{ secrets.PRIVATE_KEY }}

      - name: Build and Deploy Docker Container
        run: |
          ssh -i ${{ secrets.PRIVATE_KEY }} ubuntu@${{ env.PUBLIC_IP }} "
            docker build -t my-app .
            docker run -d -p 80:80 my-app
          "
