name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy code to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Install Docker and deploy website using Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install dependencies
            sudo apt-get -y update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

            # Add Docker's official GPG key
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

            # Add Docker repository
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            # Install Docker
            sudo apt-get -y update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

            # Ensure Docker is running
            sudo systemctl start docker
            sudo systemctl enable docker

            # Create a directory for website files
            sudo mkdir -p /var/www/html
            sudo chmod -R 755 /var/www/html

            # Copy website files to the target directory
            sudo cp -r ${{ secrets.TARGET_DIR }}/* /var/www/html/

            # Run a Docker container to host the website
            sudo docker run -d --name nginx_website -p 80:80 -v /var/www/html:/usr/share/nginx/html nginx

            # Clean up unused Docker images
            sudo docker system prune -f
